### ISSUE TITLE
Make bots interactive. 

### ISSUE THREAD

**Issue by Ephreaym** [Ephreaym/Bot-Script#19]
Add functionality to interact with the bots. Get them to escort you, attack or guard. Or maybe even switch over the flag.

**Comment by dennwc** [comment]
Just as a reminder, we have a chat hook now: [ns4.OnChat](https://pkg.go.dev/github.com/noxworld-dev/noxscript/ns/v4#OnChat).

**Comment by Ephreaym** [comment]
Yea, I’ll have to look into that. Been working mostly on getting the mana system working and changing the behavior based on mana pool.

Also fixed proper potion use. :) Will pick up on interaction a bit later.

**Comment by Ephreaym** [comment]
Resolved. Though room for improvement with new commands and functions.

**Comment by Ephreaym** [comment]
Closing this. New idea’s or improvements can be added by individual issues.
